# Generated by Django 3.0.5 on 2020-08-05 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_model', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='产品型号')),
                ('product_name', models.CharField(max_length=30, verbose_name='产品名称')),
                ('product_type', models.CharField(max_length=20, verbose_name='产品类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_num', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='项目编号')),
                ('project_name', models.CharField(max_length=30, verbose_name='项目名称')),
                ('project_manager', models.CharField(max_length=20, verbose_name='项目经理')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_num', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='任务单号')),
                ('dev_type', models.CharField(max_length=20, verbose_name='开发类型')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('task_status', models.CharField(choices=[('no', '未开始'), ('doing', '进行中'), ('done', '已完成')], max_length=10, verbose_name='任务状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_task', to='project.Product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['-task_num'],
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('vision_num', models.PositiveIntegerField(verbose_name='版本数')),
                ('vision_name', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='版本名称')),
                ('executor', models.CharField(max_length=20, verbose_name='执行人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('start_time', models.DateTimeField(blank=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='结束时间')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_vision', to='project.Task', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '版本',
                'verbose_name_plural': '版本',
                'ordering': ['vision_num'],
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='日期')),
                ('executor', models.CharField(max_length=20, verbose_name='执行人')),
                ('hours', models.FloatField(unique=True, verbose_name='工时')),
                ('record', models.TextField(unique=True, verbose_name='开发记录')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_progress', to='project.Task', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '进度',
                'verbose_name_plural': '进度',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_product', to='project.Project', verbose_name='所属项目'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='事业部')),
                ('projects', models.ManyToManyField(related_name='to_department', to='project.Project', verbose_name='项目编号')),
            ],
            options={
                'verbose_name': '事业部',
                'verbose_name_plural': '事业部',
            },
        ),
    ]
