# Generated by Django 3.0.5 on 2020-08-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
