# Generated by Django 3.0.5 on 2020-08-02 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '事业部', 'verbose_name_plural': '事业部'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-create_time'], 'verbose_name': '产品', 'verbose_name_plural': '产品'},
        ),
        migrations.AlterField(
            model_name='department',
            name='projects',
            field=models.ManyToManyField(related_name='to_department', to='project.Project', verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='product',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_product', to='project.Project', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_progress', to='project.Task', verbose_name='所属任务'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_task', to='project.Product', verbose_name='所属产品'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_vision', to='project.Task', verbose_name='所属任务'),
        ),
    ]
