# Generated by Django 3.0.5 on 2020-08-29 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='version',
            fields=[
                ('version_num', models.PositiveIntegerField(verbose_name='版本数')),
                ('version_name', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='版本名称')),
                ('executor', models.CharField(max_length=20, verbose_name='执行人')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_version', to='project.Task', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '版本',
                'verbose_name_plural': '版本',
                'ordering': ['version_num'],
            },
        ),
        migrations.DeleteModel(
            name='Vision',
        ),
    ]
