# Generated by Django 3.0.5 on 2020-08-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200802_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=30, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=20, verbose_name='产品类型'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='data',
            field=models.DateTimeField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='executor',
            field=models.CharField(max_length=20, verbose_name='执行人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.CharField(max_length=20, verbose_name='项目经理'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=30, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('no', '未开始'), ('doing', '进行中'), ('done', '已完成')], max_length=10, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='executor',
            field=models.CharField(max_length=20, verbose_name='执行人'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='vision_num',
            field=models.PositiveIntegerField(verbose_name='版本数'),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together=set(),
        ),
    ]
