# Generated by Django 3.0.5 on 2020-08-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200806_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='end_time',
            field=models.DateField(blank=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='start_time',
            field=models.DateField(blank=True, verbose_name='开始时间'),
        ),
    ]
