# Generated by Django 3.0.5 on 2020-08-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200802_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['-date'], 'verbose_name': '进度', 'verbose_name_plural': '进度'},
        ),
        migrations.RenameField(
            model_name='progress',
            old_name='data',
            new_name='date',
        ),
    ]
