# Generated by Django 3.0.5 on 2020-08-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200806_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='hours',
            field=models.FloatField(verbose_name='工时'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='record',
            field=models.TextField(verbose_name='开发记录'),
        ),
    ]
